# Generated by Django 5.2.8 on 2026-09-21 03:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('home_team_logo', models.URLField(blank=True, null=True)),
                ('away_team_logo', models.URLField(blank=True, null=True)),
                ('start_time', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='SportCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('icon_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pick',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('team_selected', models.CharField(max_length=100)),
                ('pick_type', models.CharField(max_length=50)),
                ('point_spread', models.FloatField(blank=True, null=True)),
                ('odds_american', models.IntegerField()),
                ('edge_percentage', models.FloatField(default=0.0)),
                ('ev_percentage', models.FloatField(default=0.0)),
                ('confidence_percentage', models.IntegerField(default=0)),
                ('breakdown_text', models.TextField(blank=True, null=True)),
                ('is_pick_of_the_day', models.BooleanField(db_index=True, default=False)),
                ('expert_name', models.CharField(blank=True, max_length=100, null=True)),
                ('expert_photo', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picks', to='betting.match')),
            ],
        ),
        migrations.CreateModel(
            name='SavedPick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('pick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='betting.pick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_picks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='betting.sportcategory'),
        ),
        migrations.CreateModel(
            name='UserParlay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('risk_level', models.CharField(default='Medium', max_length=20)),
                ('total_odds', models.IntegerField(default=0)),
                ('overall_confidence', models.IntegerField(default=0)),
                ('is_tracked', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('picks', models.ManyToManyField(related_name='parlays', to='betting.pick')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parlays', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='pick',
            index=models.Index(fields=['match', 'pick_type'], name='betting_pic_match_i_378f40_idx'),
        ),
        migrations.AddIndex(
            model_name='pick',
            index=models.Index(fields=['is_pick_of_the_day', '-created_at'], name='betting_pic_is_pick_e1e1eb_idx'),
        ),
        migrations.AddIndex(
            model_name='savedpick',
            index=models.Index(fields=['user', '-created_at'], name='betting_sav_user_id_492364_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='savedpick',
            unique_together={('user', 'pick')},
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['is_active', 'start_time'], name='betting_mat_is_acti_939e72_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['sport', 'is_active'], name='betting_mat_sport_i_424428_idx'),
        ),
        migrations.AddIndex(
            model_name='userparlay',
            index=models.Index(fields=['user', '-created_at'], name='betting_use_user_id_d00317_idx'),
        ),
        migrations.AddIndex(
            model_name='userparlay',
            index=models.Index(fields=['user', 'is_tracked'], name='betting_use_user_id_8d03ed_idx'),
        ),
    ]
